/**
 * @file Defines a simple key-value store for UI and message strings.
 * Since full localization is not required, this provides a centralized
 * place for text, allowing for easier management and consistency.
 * All keys should be camelCase or dot.case for structure.
 */

export const stringDB = {
    // Common UI elements
    'common.button.back': '§l§cBack§r',
    'common.button.close': '§l§cClose§r',
    'common.button.confirm': '§l§aConfirm§r',
    'common.button.cancel': '§l§cCancel§r',
    'common.button.ok': '§l§aOK§r',
    'common.boolean.yes': '§aYes§r',
    'common.boolean.no': '§cNo§r',
    'common.value.notAvailable': 'N/A',
    'common.value.player': 'Player', // Generic placeholder for player name if actual name is unavailable
    'common.value.unknown': 'Unknown',
    'common.value.noReasonProvided': 'No reason provided.',
    'common.error.genericForm': '§cAn error occurred with the form.',
    'common.error.playerNotFound': '§cPlayer "{playerName}" not found.',
    'common.error.playerNotFoundOnline': '§cPlayer "{playerName}" is not online.',
    'common.error.nameEmpty': '§cName cannot be empty.',
    'common.error.reasonEmpty': '§cReason cannot be empty.',
    'common.error.durationInvalid': '§cInvalid duration format.',
    'common.error.commandModuleNotFound': '§cError: Command module "{moduleName}" not found or not enabled.',
    'common.error.permissionDenied': '§cYou do not have permission to use this command.',
    'common.error.chatProcessingUnavailable': '§cChat processing is currently unavailable. Please try again later or contact an admin.',
    'common.success.generic': '§aAction successful.',

    // Admin Panel
    'ui.adminPanel.title': '§l§bAntiCheat Admin Panel§r',
    'ui.adminPanel.body': 'Welcome, {playerName}! Select an action:',
    'ui.adminPanel.button.viewPlayers': '§lView Online Players§r',
    'ui.adminPanel.button.inspectPlayerText': '§lInspect Player (Text)§r',
    'ui.adminPanel.button.resetFlagsText': '§lReset Player Flags (Text)§r',
    'ui.adminPanel.button.listWatched': '§lList Watched Players§r',
    'ui.adminPanel.button.serverManagement': '§lServer Management§r',
    'ui.adminPanel.button.editConfig': '§l§6Edit Configuration§r (Owner)',
    'ui.adminPanel.error.generic': '§cError displaying admin panel.',

    // Normal User Panel
    'ui.normalPanel.title': '§l§aPlayer Panel§r',
    'ui.normalPanel.body': 'Welcome, {playerName}!',
    'ui.normalPanel.button.myStats': '§bMy Stats§r',
    'ui.normalPanel.button.serverRules': '§eServer Rules§r',
    'ui.normalPanel.button.helpLinks': '§9Helpful Links§r',

    // My Stats UI
    'ui.myStats.title': '§l§bYour Stats§r',
    'ui.myStats.body': 'Session Playtime: {playtime}',
    'ui.myStats.labelLocation': 'Location: X: {x}, Y: {y}, Z: {z}',
    'ui.myStats.labelDimension': 'Dimension: {dimensionName}',

    // Server Rules UI
    'ui.serverRules.title': '§l§eServer Rules§r',
    'ui.serverRules.noRulesDefined': 'No server rules have been defined by the admin yet.',

    // Helpful Links UI
    'ui.helpfulLinks.title': '§l§9Helpful Links§r',
    'ui.helpfulLinks.body': 'Select a link to view it in chat:',
    'ui.helpfulLinks.noLinks': 'No helpful links have been configured by the admin.',
    'ui.helpfulLinks.linkMessageFormat': '§e{title}: §9§n{url}§r (Copy and paste into your browser)',

    // Online Players List
    'ui.onlinePlayers.title': '§l§bOnline Players ({count})§r',
    'ui.onlinePlayers.body': 'Select a player to manage:',
    'ui.onlinePlayers.noPlayers': 'No players are currently online.',
    'ui.onlinePlayers.button.playerEntry': '{playerName} §7(Flags: {flagCount})§r',
    'ui.button.backToAdminPanel': '§l§cBack to Admin Panel§r',
    'ui.onlinePlayers.error.generic': '§cError displaying online players list.',

    // Inspect Player Form (Text Input)
    'ui.inspectPlayerForm.title': '§l§3Inspect Player§r',
    'ui.inspectPlayerForm.textField.label': 'Player Name:',
    'ui.inspectPlayerForm.textField.placeholder': 'Enter exact player name',

    // Player Actions Form
    'ui.playerActions.title': '§l§6Actions for {targetPlayerName}§r',
    'ui.playerActions.body': 'Flags: {flags} | Watched: {watchedStatus}',
    'ui.playerActions.button.viewFlags': '§bView Detailed Flags§r',
    'ui.playerActions.button.viewInventory': '§3View Inventory§r',
    'ui.playerActions.button.teleportTo': '§dTeleport To Player§r',
    'ui.playerActions.button.teleportHere': '§dTeleport Player Here§r',
    'ui.playerActions.button.kick': '§cKick Player§r',
    'ui.playerActions.button.freeze': '§bFreeze Player§r',
    'ui.playerActions.button.unfreeze': '§aUnfreeze Player§r',
    'ui.playerActions.button.mute': '§6Mute Player§r',
    'ui.playerActions.button.unmutePermanent': '§aUnmute (Permanent)§r',
    'ui.playerActions.button.unmuteTimed': '§aUnmute (Expires: {expiryDate})§r',
    'ui.playerActions.button.ban': '§4Ban Player§r',
    'ui.playerActions.button.resetFlags': '§eReset All Flags§r',
    'ui.playerActions.button.clearInventory': '§cClear Inventory§r',
    'ui.playerActions.button.backToList': '§l§cBack to Player List§r',
    'ui.playerActions.teleport.error': '§cTeleport failed: {error}',
    'ui.playerActions.teleportTo.success': '§aTeleported to {targetPlayerName}.',
    'ui.playerActions.teleportHere.success': '§aTeleported {targetPlayerName} to you.',
    'ui.playerActions.teleportHere.targetNotification': '§eYou have been teleported by an admin.',
    'ui.playerActions.kick.title': '§l§cKick {targetPlayerName}§r',
    'ui.playerActions.kick.reasonPrompt': 'Reason for kicking (optional):',
    'ui.playerActions.kick.reasonPlaceholder': 'Enter kick reason',
    'ui.playerActions.kick.cancelled': '§7Kick action cancelled.',
    'ui.playerActions.mute.title': '§l§6Mute {targetPlayerName}§r',
    'ui.playerActions.mute.durationPrompt': 'Mute duration (e.g., 30s, 5m, 1h, perm):',
    'ui.playerActions.mute.durationPlaceholder': 'Enter duration or "perm"',
    'ui.playerActions.mute.reasonPrompt': 'Reason for muting (optional):',
    'ui.playerActions.mute.reasonPlaceholder': 'Enter mute reason',
    'ui.playerActions.mute.cancelled': '§7Mute action cancelled.',
    'ui.playerActions.ban.title': '§l§4Ban {targetPlayerName}§r',
    'ui.playerActions.ban.durationPrompt': 'Ban duration (e.g., 7d, 1mo, perm):',
    'ui.playerActions.ban.durationPlaceholder': 'Enter duration or "perm"',
    'ui.playerActions.ban.reasonPrompt': 'Reason for banning:',
    'ui.playerActions.ban.reasonPlaceholder': 'Enter ban reason',
    'ui.playerActions.ban.cancelled': '§7Ban action cancelled.',
    'ui.playerActions.clearInventory.confirmTitle': '§l§cConfirm Clear Inventory§r',
    'ui.playerActions.clearInventory.confirmBody': 'Are you sure you want to clear the inventory of {targetPlayerName}? This cannot be undone.',
    'ui.playerActions.clearInventory.confirmToggle': '§cConfirm Clear Inventory',
    'ui.playerActions.clearInventory.success': '§aInventory of {targetPlayerName} cleared.',
    'ui.playerActions.clearInventory.fail': '§cFailed to clear inventory for {targetPlayerName}.',
    'ui.playerActions.error.invalidSelection': '§cInvalid selection.',
    'ui.playerActions.error.generic': '§cAn error occurred performing the player action.',

    // Detailed Flags Form
    'ui.detailedFlags.title': '§l§3Flags for {playerName}§r',
    'ui.detailedFlags.noFlags': 'No flags recorded for this player.',
    'ui.detailedFlags.flagEntry': '§e{flagName}: §f{count} §7(Last: {lastDetectionTime})§r',

    // Confirmation Modal (Generic)
    'ui.common.actionCancelled': '§7Action cancelled.',

    // Server Management
    'ui.serverManagement.title': '§l§6Server Management§r',
    'ui.serverManagement.body': 'Select a server management action:',
    'ui.serverManagement.button.systemInfo': '§bSystem Information§r',
    'ui.serverManagement.button.clearChat': '§eClear Global Chat§r',
    'ui.serverManagement.button.lagClear': '§cClear Ground Items/Entities§r',
    'ui.serverManagement.button.actionLogs': '§3View Action Logs (All)§r',
    'ui.serverManagement.button.modLogs': '§3View Moderation Logs (Filtered)§r',
    'ui.serverManagement.button.editConfig': '§l§6Edit Configuration§r (Owner)',
    'ui.serverManagement.button.backToAdminPanel': '§l§cBack to Admin Panel§r',
    'ui.serverManagement.clearChat.confirmTitle': '§l§cConfirm Clear Chat§r',
    'ui.serverManagement.clearChat.confirmBody': 'Are you sure you want to clear the global chat for all players?',
    'ui.serverManagement.clearChat.confirmToggle': '§cConfirm Clear Chat',
    'ui.serverManagement.lagClear.confirmTitle': '§l§cConfirm Lag Clear§r',
    'ui.serverManagement.lagClear.confirmBody': 'Are you sure you want to clear all ground items and non-player/non-persistent entities? This may cause lag temporarily.',
    'ui.serverManagement.lagClear.confirmToggle': '§cConfirm Lag Clear',
    'ui.serverManagement.error.generic': '§cError in server management action.',

    // System Info
    'ui.systemInfo.title': '§l§bSystem Information§r',
    'ui.systemInfo.entry.acVersion': '§aAntiCheat Version:§r §e{version}',
    'ui.systemInfo.entry.mcVersion': '§aMinecraft Version:§r §e{version}',
    'ui.systemInfo.entry.serverTime': '§aCurrent Server Time:§r §e{time}',
    'ui.systemInfo.label.currentTick': '§aCurrent Game Tick:',
    'ui.systemInfo.label.worldTime': '§aCurrent World Time:',
    'ui.systemInfo.entry.onlinePlayers': '§aOnline Players:§r §e{onlinePlayers} / {maxPlayers}',
    'ui.systemInfo.entry.totalPlayerData': '§aCached PlayerData Entries:§r §e{count}',
    'ui.systemInfo.entry.watchedPlayers': '§aWatched Players (Online):§r §e{count}',
    'ui.systemInfo.entry.mutedPersistent': '§aActive Mutes (Persistent):§r §e{count}',
    'ui.systemInfo.entry.bannedPersistent': '§aActive Bans (Persistent):§r §e{count}',
    'ui.systemInfo.entry.activeWorldBorders': '§aActive World Borders:§r §e{count}',
    'ui.systemInfo.entry.logManagerEntries': '§aLogManager Entries (In-Memory):§r §e{count}',
    'ui.systemInfo.entry.reportManagerEntries': '§aReportManager Entries (In-Memory):§r §e{count}',
    'ui.systemInfo.button.backToServerMgmt': '§l§cBack to Server Management§r',

    // Config Editor
    'ui.configEditor.title': '§l§6Configuration Editor§r (Owner Only)',
    'ui.configEditor.body': 'Select a configuration key to edit its value. Changes apply at runtime.',
    'ui.configEditor.button.format': '§e{key} §7({type}): §f{value}',
    'ui.configEditor.button.formatTruncated': '§e{key} §7({type}): §f{value}...',
    'ui.configEditor.button.objectPlaceholder': '§o(Complex Object/Array)§r',
    'ui.configEditor.button.backToAdminPanel': '§l§cBack to Server Management§r',
    'ui.configEditor.error.ownerOnly': '§cOnly the server owner can edit the configuration.',
    'ui.configEditor.error.generic': '§cError displaying config editor.',
    'ui.configEditor.error.invalidSelection': '§cInvalid selection in config editor.',
    'ui.configEditor.error.nonArrayObject': '§cCannot edit non-array objects directly ({keyName}). Use specific commands if available.',
    'ui.configEditor.error.nonArrayObjectEdit': '§cDirect editing of complex objects for "{keyName}" is not supported via this UI. Arrays of simple types are supported.',
    'ui.configEditor.valueInput.title': '§l§6Edit: {keyName}§r',
    'ui.configEditor.valueInput.boolean.label': 'New value for {keyName} (boolean: true/false):',
    'ui.configEditor.valueInput.string.label': 'New value for {keyName} (string):',
    'ui.configEditor.valueInput.string.placeholder': 'Enter new string value',
    'ui.configEditor.valueInput.number.label': 'New value for {keyName} (number):',
    'ui.configEditor.valueInput.number.placeholder': 'Enter new numeric value',
    'ui.configEditor.valueInput.array.label': 'New value for {keyName} (array - JSON format or comma-separated for simple types):',
    'ui.configEditor.valueInput.array.placeholder': 'e.g., ["a","b"] or 1,2,3',
    'ui.configEditor.valueInput.error.typeUnknown': '§cCannot edit type "{type}" for key "{keyName}" via this UI.',
    'ui.configEditor.valueInput.error.notANumber': '§cInvalid input. Please enter a valid number.',
    'ui.configEditor.valueInput.error.notAnArray': '§cInvalid input. Please enter a valid JSON array (e.g., ["item1", "item2"] or [1, 2, 3]).',
    'ui.configEditor.valueInput.error.jsonFormat': '§cInvalid JSON format for array: {error}',
    'ui.configEditor.valueInput.error.updateFailed': '§cFailed to update "{keyName}": {reason}.',
    'ui.configEditor.valueInput.error.updateFailedInternal': '§cFailed to update "{keyName}" due to an internal error.',
    'ui.configEditor.valueInput.noChange': '§eNo change detected for "{keyName}". Value remains the same.',
    'ui.configEditor.valueInput.success': '§aSuccessfully updated "{keyName}" to: {value}.',
    'ui.configEditor.valueInput.error.generic': '§cError updating config value for "{keyName}".',

    // Reset Flags Form (Text Input)
    'ui.resetFlagsForm.title': '§l§eReset Player Flags§r',
    'ui.resetFlagsForm.textField.label': 'Player Name to Reset Flags For:',
    'ui.resetFlagsForm.textField.placeholder': 'Enter exact player name',
    'ui.resetFlagsForm.toggle.label': '§cConfirm Resetting All Flags',
    'ui.resetFlagsForm.cancelled': '§7Flag reset action cancelled.',
    'ui.resetFlagsForm.error.nameEmpty': '§cPlayer name cannot be empty.',
    'ui.resetFlagsForm.error.generic': '§cError processing flag reset.',

    // Watched Players List
    'ui.watchedPlayers.title': '§l§bWatched Players§r',
    'ui.watchedPlayers.header': 'Currently watched players (online):\n',
    'ui.watchedPlayers.noPlayers': 'No players are currently being watched or online.',
    'ui.watchedPlayers.playerEntry': '- {playerName}',
    'ui.watchedPlayers.button.ok': '§l§aOK§r',

    // Action Logs / Mod Logs
    'ui.actionLogs.title': '§l§3Action Logs (All)§r',
    'ui.actionLogs.bodyHeader': 'Recent server actions:\n',
    'ui.actionLogs.noLogs': 'No logs found matching criteria.',
    'ui.actionLogs.logEntry': '§7[{timestamp}] §e{actor} §f{actionType} §b{target}§r{duration}{reason}{details}',
    'ui.actionLogs.logEntry.duration': ' (Duration: {duration})',
    'ui.actionLogs.logEntry.reason': ' (Reason: {reason})',
    'ui.actionLogs.logEntry.details': ' (Details: {details})',
    'ui.actionLogs.footer.showingLatest': '\n§o(Showing latest {count} entries. More may exist.)§r',
    'ui.actionLogs.body.empty': 'No action logs available.',
    'ui.actionLogs.button.backToServerMgmt': '§l§cBack to Server Management§r',

    'ui.modLogSelect.title': '§l§3Moderation Log Viewer§r',
    'ui.modLogSelect.body.all': 'Select log type or filter by player name.',
    'ui.modLogSelect.body.filtered': 'Showing logs for "{filterName}". Select type or clear filter.',
    'ui.modLogSelect.button.banUnban': '§cBans/Unbans§r',
    'ui.modLogSelect.button.muteUnmute': '§6Mutes/Unmutes§r',
    'ui.modLogSelect.button.filterByName': '§bFilter by Player Name§r',
    'ui.modLogSelect.button.clearFilter': '§eClear Filter ({filterName})§r',
    'ui.modLogSelect.button.backToServerMgmt': '§l§cBack to Server Management§r',
    'ui.modLogSelect.filterModal.title': '§l§bFilter Logs by Player Name§r',
    'ui.modLogSelect.filterModal.textField.label': 'Player Name (leave blank to clear):',
    'ui.modLogSelect.filterModal.textField.placeholder': 'Enter player name',
    'ui.modLogSelect.filterModal.filterSet': '§aLog filter set to: {filterName}.',
    'ui.modLogSelect.filterModal.filterCleared': '§eLog filter cleared.',
    'ui.modLogSelect.filterModal.filterBlank': '§eLog filter cannot be blank, cleared instead.',
    'ui.modLogSelect.error.generic': '§cError with mod log selection.',

    'ui.logViewer.title.banUnban': '§l§cBan/Unban Logs§r',
    'ui.logViewer.title.muteUnmute': '§l§6Mute/Unmute Logs§r',
    'ui.logViewer.title.filtered': '§l§3{logTypeName} for {filterName}§r',
    'ui.logViewer.noLogs': 'No logs found matching your criteria.',
    'ui.logViewer.button.backToLogSelect': '§l§cBack to Log Selection§r',

    // Player Data Manager specific (used by its functions, not directly UI)
    'playerData.mute.defaultReason': 'Muted by system.',
    'playerData.ban.defaultReason': 'Banned by system.',

    // TPA Manager Messages
    'tpa.manager.error.targetOfflineOnAccept': '§cTarget player {offlinePlayerName} went offline. TPA cancelled.',
    'tpa.manager.warmupMessage': '§eTeleporting in {warmupSeconds}s. Don\'t move or take damage!',
    'tpa.manager.requester.accepted': '§a{targetPlayerName} accepted your TPA request! {warmupMessage}',
    'tpa.manager.target.acceptedFromRequester': '§aYou accepted {requesterPlayerName}\'s TPA request. They will teleport in {warmupSeconds}s.',
    'tpa.manager.target.acceptedByRequester': '§a{requesterPlayerName} accepted your TPAHere request! {warmupMessage}',
    'tpa.manager.requester.acceptedHere': '§aYou accepted {targetPlayerName}\'s TPAHere request. They will teleport in {warmupSeconds}s.',
    'tpa.manager.error.teleportTargetOffline': '§cCannot teleport: {offlinePlayerName} is no longer online.',
    'tpa.manager.teleport.successToTarget': '§aSuccessfully teleported to {targetPlayerName}.',
    'tpa.manager.teleport.successTargetNotified': '§a{requesterPlayerName} has teleported to you.',
    'tpa.manager.teleport.successToRequester': '§aSuccessfully teleported to {requesterPlayerName}.',
    'tpa.manager.teleport.successRequesterNotified': '§a{targetPlayerName} has teleported to you.',
    'tpa.manager.error.teleportGenericErrorToRequester': '§cTeleport failed due to an unexpected error.',
    'tpa.manager.error.teleportGenericErrorToTarget': '§cTeleport for {otherPlayerName} failed due to an unexpected error.',
    'tpa.manager.warmupCancelledDamage.player': '§cTPA cancelled: You took damage ({damageCause}) during warm-up!',
    'tpa.manager.warmupCancelledMovement.player': '§cTPA cancelled: You moved during warm-up!',
    'tpa.manager.decline.requesterNotified': '§c{targetPlayerName} declined your TPA request.',
    'tpa.manager.decline.targetNotified': '§cYou declined {requesterPlayerName}\'s TPA request.',
    'tpa.manager.decline.otherCancelledRequester': '§cYour TPA request to {targetPlayerName} was cancelled.',
    'tpa.manager.decline.otherCancelledTarget': '§cThe TPA request from {requesterPlayerName} was cancelled.',
    'tpa.manager.expired.requesterNotified': '§cYour TPA request to {targetName} has expired.',
    'tpa.manager.expired.targetNotified': '§cThe TPA request from {requesterName} has expired.',

    // Command specific: addrank
    'command.addrank.usage': '§cUsage: {prefix}addrank <playername> <rankId>',
    'command.addrank.playerNotFound': "§cPlayer '{playerName}' not found.",
    'command.addrank.rankIdInvalid': "§cRank ID '{rankId}' is not a valid rank.",
    'command.addrank.rankNotManuallyAssignable': "§cRank '{rankName}' cannot be assigned using this command (not configured for manual tag assignment).",
    'command.addrank.permissionDeniedAssign': "§cYou do not have permission to assign the rank '{rankName}'.",
    'command.addrank.alreadyHasRank': "§ePlayer {playerName} already has the rank '{rankName}'.",
    'command.addrank.assignSuccessToIssuer': "§aSuccessfully assigned rank '{rankName}' to {playerName}.",
    'command.addrank.assignSuccessToTarget': "§aYou have been assigned the rank: {rankName}.",
    'command.addrank.errorAssign': "§cAn error occurred while assigning the rank: {errorMessage}",

    // Command specific: ban
    'command.ban.usage': "§cUsage: {prefix}ban <playername> [duration] [reason]",
    'command.ban.playerNotFound': "§cPlayer '{playerName}' not found.",
    'command.ban.cannotBanSelf': "§cYou cannot ban yourself.",
    'command.ban.permissionDeniedAdminOwner': "§cYou do not have permission to ban an admin or owner.",
    'command.ban.permissionDeniedOwner': "§cYou do not have permission to ban an owner.",
    'command.ban.ownerCannotBanOwner': "§cOwners cannot ban other owners through this command.",
    'command.ban.invalidDuration': "§cInvalid duration format. Use: 7d, 2h, 30m, or perm.",
    'command.ban.kickMessage.header': "§cYou have been banned from the server.",
    'command.ban.kickMessage.reason': "§eReason: §f{reason}",
    'command.ban.kickMessage.bannedBy': "§eBanned by: §f{bannedBy}",
    'command.ban.kickMessage.duration': "§eDuration: §f{durationDisplay}",
    'command.ban.kickMessage.appeal': "§eAppeal on Discord: §9{discordLink}",
    'command.ban.success': "§aSuccessfully banned {playerName} for {durationString}. Reason: {reason}",
    'command.ban.failure': "§cFailed to ban {playerName}. They might already be banned or an error occurred.",

    // Command specific: clearchat
    'command.clearchat.failPartial': "§cChat clear failed partially. Some messages might remain.",
    'command.clearchat.success': "§aChat cleared successfully.",

    // Command specific: clearreports
    'command.clearreports.usage': "§cUsage: {prefix}{syntax}",
    'command.clearreports.example': "§cExample: {prefix}clearreports <report_id> OR {prefix}clearreports <player_name> OR {prefix}clearreports all",
    'command.clearreports.allSuccess': "§aSuccessfully cleared all {count} reports.",
    'command.clearreports.idSuccess': "§aReport with ID '{reportId}' has been cleared.",
    'command.clearreports.idNotFound': "§cReport with ID '{reportId}' not found.",
    'command.clearreports.playerSuccess': "§aCleared {count} reports associated with player '{playerName}'.",
    'command.clearreports.playerNotFound': "§eNo reports found associated with player '{playerName}'.",

    // Configurable value descriptions (for potential UI)
    'config.key.chatClearLinesCount.title': "Chat Clear Lines Count",
    'config.key.chatClearLinesCount.description': "Number of empty lines sent by !clearchat command to clear chat.",
    'config.key.reportsViewPerPage.title': "Reports View Per Page",
    'config.key.reportsViewPerPage.description': "Number of reports displayed per page in the !viewreports command.",

    // Add more string keys and their corresponding text here as needed.
    // Example: 'some.module.someMessage': 'This is a message for {placeholder}.'
};
