name: Release mcaddon
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract version from tag
        shell: bash
        run: |
          set -e
          RAW_TAG_NAME="${{ github.ref_name }}"
          echo "FULL_TAG_NAME=$RAW_TAG_NAME" >> $GITHUB_ENV

          # Check for -beta suffix
          IS_BETA="false"
          if [[ "$RAW_TAG_NAME" == *"-beta" ]]; then
            IS_BETA="true"
          fi
          echo "IS_BETA_RELEASE=$IS_BETA" >> $GITHUB_ENV

          # Strip 'v' prefix and '-beta' suffix to get the clean version string
          VERSION_STR="${RAW_TAG_NAME#v}"
          VERSION_STR="${VERSION_STR%-beta}"
          echo "VERSION_STRING=$VERSION_STR" >> $GITHUB_ENV

          # Create version array string
          VERSION_ARR_STR="[$(echo "$VERSION_STR" | tr '.' ',')]"
          echo "VERSION_ARRAY_STRING=$VERSION_ARR_STR" >> $GITHUB_ENV

          echo "Full tag: $RAW_TAG_NAME"
          echo "Is Beta: $IS_BETA"
          echo "Clean Version String: $VERSION_STR"
          echo "Version Array String: $VERSION_ARR_STR"

      - name: Create staging directory and copy addon folders
        run: |
          set -e
          mkdir staging
          cp -r AddonExeBP staging/
          cp -r AddonExeRP staging/

      - name: Replace placeholders in staged files
        shell: bash
        env:
          VERSION_STRING: ${{ env.VERSION_STRING }}
          VERSION_ARRAY_STRING: ${{ env.VERSION_ARRAY_STRING }}
          IS_BETA_RELEASE: ${{ env.IS_BETA_RELEASE }}
        run: |
          set -e
          echo "--- Starting Placeholder Replacement ---"
          BP_MANIFEST="staging/AddonExeBP/manifest.json"
          RP_MANIFEST="staging/AddonExeRP/manifest.json"
          CONFIG_JS_PATH="staging/AddonExeBP/scripts/config.js"

          # Replace version array placeholder in all relevant files
          sed -i "s|\"version\": \[1, 0, 0\]|\"version\": ${VERSION_ARRAY_STRING}|g" "$BP_MANIFEST"
          sed -i "s|\"version\": \[1, 0, 0\]|\"version\": ${VERSION_ARRAY_STRING}|g" "$RP_MANIFEST"
          sed -i "s|version: \[1, 0, 0\]|version: ${VERSION_ARRAY_STRING}|g" "$CONFIG_JS_PATH"

          # Replace version string in descriptions
          sed -i "s|v1.0.0|v${VERSION_STRING}|g" "$BP_MANIFEST" "$RP_MANIFEST"

          # Conditionally modify config for beta releases
          if [ "${IS_BETA_RELEASE}" = "true" ]; then
            echo "--- Applying Beta Release Modifications ---"
            sed -i "s|ownerPlayerNames: \['Your•Name•Here'\]|ownerPlayerNames: \['SjnTechMlmYT'\]|g" "$CONFIG_JS_PATH"
            sed -i "s|debug: false|debug: true|g" "$CONFIG_JS_PATH"
            echo "Beta modifications applied."
          fi

          echo "--- Verification ---"
          echo "BP Manifest:"
          cat "$BP_MANIFEST"
          echo "RP Manifest:"
          cat "$RP_MANIFEST"
          echo "Config.js:"
          head -n 15 "$CONFIG_JS_PATH"
          echo "--- End Verification ---"

      - name: Create Release Archives
        shell: bash
        env:
          FULL_TAG_NAME: ${{ env.FULL_TAG_NAME }}
        run: |
          set -e
          # Create main .mcaddon
          (cd staging && zip -r "../AddonExe.${FULL_TAG_NAME}.mcaddon" ./*)

          # Create BP .mcpack
          (cd staging/AddonExeBP && zip -r "../../AddonExe.BP${FULL_TAG_NAME}.mcpack" ./*)

          # Create RP .mcpack
          (cd staging/AddonExeRP && zip -r "../../AddonExe.RP${FULL_TAG_NAME}.mcpack" ./*)
          echo "Created release archives."

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./AddonExe.${{ env.FULL_TAG_NAME }}.mcaddon
            ./AddonExe.BP${{ env.FULL_TAG_NAME }}.mcpack
            ./AddonExe.RP${{ env.FULL_TAG_NAME }}.mcpack
