name: Release mcaddon
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js and cache npm dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify a Node.js version
          cache: 'npm'
      - run: npm install # Install dependencies

      - name: Create Changelog
        uses: anothrNick/github-tag-action@1.69.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Extract version from tag
        shell: bash
        run: |
          RAW_TAG_NAME="${{ github.ref_name }}"
          echo "FULL_TAG_NAME=$RAW_TAG_NAME" >> $GITHUB_ENV
          # Remove 'v' or 'V' prefix for version string
          if [[ "$RAW_TAG_NAME" == v* ]]; then
            VERSION_STR="${RAW_TAG_NAME#v}"
          elif [[ "$RAW_TAG_NAME" == V* ]]; then
            VERSION_STR="${RAW_TAG_NAME#V}"
          else
            VERSION_STR="$RAW_TAG_NAME"
          fi
          echo "VERSION_STRING=$VERSION_STR" >> $GITHUB_ENV
          echo "Extracted VERSION_STRING: $VERSION_STR"
          # Convert version string "1.2.3" to array string "[1,2,3]"
          if [ -z "$VERSION_STR" ]; then
            echo "Warning: VERSION_STRING is empty. VERSION_ARRAY_STRING will be '[]'."
            VERSION_ARR_STR="[]"
          else
            VERSION_ARR_STR="[$(echo "$VERSION_STR" | tr '.' ',')]"
          fi
          echo "VERSION_ARRAY_STRING=$VERSION_ARR_STR" >> $GITHUB_ENV
          echo "Full tag: $RAW_TAG_NAME, Extracted version string: $VERSION_STR, Resulting version array string: $VERSION_ARR_STR"

      - name: Create staging directory and copy addon folders
        run: |
          mkdir staging
          cp -r AntiCheatsBP staging/
          cp -r AntiCheatsRP staging/

      - name: Replace placeholders in staged files
        shell: bash
        env:
          VERSION_STRING: ${{ env.VERSION_STRING }}
          VERSION_ARRAY_STRING: ${{ env.VERSION_ARRAY_STRING }}
        run: |
          echo "--- Starting Placeholder Replacement ---"
          BP_MANIFEST="staging/AntiCheatsBP/manifest.json"
          RP_MANIFEST="staging/AntiCheatsRP/manifest.json"
          CONFIG_JS_PATH="staging/AntiCheatsBP/scripts/config.js"

          # Replace in JSON files
          find staging -type f -name "*.json" -exec sed -i "s/v__VERSION_STRING__/v${VERSION_STRING}/g" {} +
          find staging -type f -name "*.json" -exec sed -i "s/\"__VERSION_ARRAY__\"/${VERSION_ARRAY_STRING}/g" {} +

          # Replace in JS config
          sed -i "s/v__VERSION_STRING__/v${VERSION_STRING}/g" "$CONFIG_JS_PATH"

          echo "--- Verification ---"
          echo "BP Manifest:"
          cat "$BP_MANIFEST"
          echo "RP Manifest:"
          cat "$RP_MANIFEST"
          echo "Config.js:"
          head -n 15 "$CONFIG_JS_PATH"
          echo "--- End Verification ---"

      - name: Create Release Archives
        shell: bash
        env:
          FULL_TAG_NAME: ${{ env.FULL_TAG_NAME }}
        run: |
          # Create main .mcaddon
          (cd staging && zip -r "../AC.${FULL_TAG_NAME}.mcaddon" ./*)

          # Create BP .mcpack
          (cd staging/AntiCheatsBP && zip -r "../../AC BP${FULL_TAG_NAME}.mcpack" ./*)

          # Create RP .mcpack
          (cd staging/AntiCheatsRP && zip -r "../../AC RP${FULL_TAG_NAME}.mcpack" ./*)
          echo "Created release archives."

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./AC.${{ env.FULL_TAG_NAME }}.mcaddon
            ./AC BP${{ env.FULL_TAG_NAME }}.mcpack
            ./AC RP${{ env.FULL_TAG_NAME }}.mcpack
